// Code generated by the Encore v1.57.13 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-936eu.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the 936eu Encore application.
 */
export default class Client {
    public readonly about: about.ServiceClient
    public readonly agent: agent.ServiceClient
    public readonly metrics: metrics.ServiceClient
    public readonly notes: notes.ServiceClient
    public readonly system: system.ServiceClient
    public readonly trace: trace.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.about = new about.ServiceClient(base)
        this.agent = new agent.ServiceClient(base)
        this.metrics = new metrics.ServiceClient(base)
        this.notes = new notes.ServiceClient(base)
        this.system = new system.ServiceClient(base)
        this.trace = new trace.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

export namespace about {
    export interface GetAboutResponse {
        /**
         * GitHub 用户名;头像取 https://github.com/<user>.png,空字符串 = 未配置
         */
        githubUser: string

        /**
         * 第二条外链(画板 2e 的 GitHub 按钮旁);空字符串 = 不渲染那个按钮
         */
        originUrl: string

        intro: string
        /**
         * 「本站如何构建」逐条
         */
        buildPoints: string[]

        /**
         * 「公开仓库」卡片
         */
        repos: RepoCard[]

        /**
         * 底部语言构成条
         */
        langBar: LangSlice[]

        /**
         * ISO 8601;从未设置过时为 null
         */
        updatedAt: string | null
    }

    export interface LangSlice {
        name: string
        /**
         * 语言条占比,0–100
         */
        pct: number

        color: string
    }

    export interface RepoCard {
        name: string
        lang: string
        /**
         * 语言圆点色,#RRGGBB
         */
        dot: string

        stars: number
        desc: string
        /**
         * 最近推送日期的展示文本(画板 2e 右下角)
         */
        pushed: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.get = this.get.bind(this)
        }

        public async get(): Promise<GetAboutResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/about`)
            return await resp.json() as GetAboutResponse
        }
    }
}

export namespace agent {
    export interface ChatMessage {
        seq: number
        role: "user" | "assistant" | "tool"
        content: string
        /**
         * ISO 8601
         */
        createdAt: string
    }

    export interface CreateSessionResponse {
        session: SessionSummary
        visitorCookie: string
    }

    export interface DeleteSessionResponse {
        visitorCookie: string
    }

    export interface GetSessionResponse {
        session: SessionSummary
        /**
         * 会话内历史消息,按 seq 有序(刷新后恢复对话)
         */
        messages: ChatMessage[]

        visitorCookie: string
    }

    export interface ListSessionsRequest {
        /**
         * 默认 50,上限 200
         */
        limit?: number
    }

    export interface ListSessionsResponse {
        sessions: SessionSummary[]
        visitorCookie?: string
    }

    export interface SessionSummary {
        id: string
        title: string
        /**
         * ISO 8601
         */
        createdAt: string

        /**
         * ISO 8601
         */
        lastActiveAt: string
    }

    /**
     * 面板上一条工具的全部内容。字段集就是白名单:多一个要在 `publicEntry` 里点名。
     */
    export interface ToolCatalogEntry {
        name: string
        label: string
        description: string
        group: ToolGroup
        /**
         * 入参 JSON Schema,与工具定义里的**同一份**(测试逐字段钉死)
         */
        parameters: ToolParametersSchema

        /**
         * 输出形态说明
         */
        output: string

        /**
         * 输出形态的补充(上限 / 边界情形)
         */
        outputNote?: string

        /**
         * 执行期间会上报的阶段文案(按顺序);只有会上报进度的工具才有
         */
        phases?: string[]
    }

    export interface ToolCatalogResponse {
        /**
         * 按分组顺序:纯函数组 → 外呼组 → 会话绑定组;组内按注册顺序
         */
        tools: ToolCatalogEntry[]

        /**
         * 单个工具结果**正文**的字符上限(`capText` 的预算),面板脚注「工具结果正文统一 N 字符上限」用。
         * 
         * 【是正文预算,不是整段结果的长度】(codex 初审 P2)`capText` 超限时把正文截到 N 字符,
         * **再追加一行显式的截断标注**(「…(已截断,原文共 M 字符)」),标注不计入 N。
         * 所以模型 / 轨迹面板实际拿到的文本可以略长于 N —— 这里公开的是「正文最多这么多」这条契约,
         * 不是「结果总长不超过」。catalog.test.ts 把这条语义钉死(N 字符不截;N+1 字符 = 前 N 字符原样 + 标注)。
         * 
         * 是代码常量不是配置值(不在库里、不在 env 里,设计稿上本来就印着),
         * 从源头取而不是前端写死 —— 否则它就是「第二个要改的地方」。
         */
        resultBodyCharLimit: number
    }

    /**
     * 工具分组 = 注册路径(docs/security.md §1「工具分两组」+ R-TITLE 补记的第三档):
     * pure     —— 在 `TOOL_REGISTRY`(纯函数组:只读 notes 三张表,不联网)
     * outbound —— 经 `makeWebSearchTool` / `makeGenerateImageTool` 构造(外呼组:持服务端凭据打白名单域;
     * `generate_image` 同时按会话绑定,但它的**性质**是外呼 —— 分组按「凭据从哪来」判)
     * session  —— 在 `SESSION_TOOL_REGISTRY`(会话绑定组:闭包绑定会话 id,只写本会话标题)
     * 前端按这个值挑分组文案与颜色,**不按工具名**。
     */
    export type ToolGroup = "pure" | "outbound" | "session"

    /**
     * 单个入参的 JSON Schema 子集。**只列本仓库工具实际用到的关键字**:类型不认的关键字进不了
     * META,也就进不了面板 —— 想用新关键字先扩这里,前端才知道怎么画它。
     */
    export interface ToolParamSchema {
        type: "string" | "integer"
        description: string
        minLength?: number
        maxLength?: number
        minimum?: number
        maximum?: number
    }

    /**
     * 工具入参 schema:一律 object 且 `additionalProperties: false`(不接受未声明字段)。
     */
    export interface ToolParametersSchema {
        type: "object"
        properties: { [key: string]: ToolParamSchema }
        required: string[]
        additionalProperties: false
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.ask = this.ask.bind(this)
            this.createSession = this.createSession.bind(this)
            this.deleteSession = this.deleteSession.bind(this)
            this.getSession = this.getSession.bind(this)
            this.image = this.image.bind(this)
            this.listSessions = this.listSessions.bind(this)
            this.listTools = this.listTools.bind(this)
        }

        public async ask(method: "POST", body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/agent/ask`, body, options)
        }

        /**
         * 创建会话(标题留空,由首条用户消息派生)。
         * 
         * **这是两个会发放新访客身份的地方之一**(另一个是 `/agent/ask` 建新会话时)。
         * 会话必然属于某个访客,所以这里用 `ensureVisitor` 而不是 `resolveVisitor`。
         */
        public async createSession(): Promise<CreateSessionResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/agent/sessions`)

            //Populate the return object from the JSON body and received headers
            const rtn = await resp.json() as CreateSessionResponse
            if (!BROWSER) {
                rtn.visitorCookie = mustBeSet("Header `set-cookie`", resp.headers.getSetCookie()[0])
            }
            return rtn
        }

        /**
         * 删除本访客的一个会话(R-VISITOR;所有者裁定新增,设计稿没有这个入口)。
         * 
         * 硬删,`messages` / `trace_events` 由外键级联清掉 —— 这是隐私功能,
         * 「删了但还在库里」不满足访客按下那个按钮时的预期(store.deleteSession)。
         * 
         * 删不到(不存在 / 不是本访客的)一律 `not_found`:与 `getSession` 同一个口径,
         * 不让删除端点变成一个「这个 id 存在吗」的探测器。
         * 
         * 【顺序敏感:先判归属,再动运行时会话,最后删库行】
         * - 归属必须排在最前:否则任何人都能拿一个别人的 id 把对方内存里的 pi 会话 dispose 掉,
         * 那是一条不需要任何凭据的拒绝服务。
         * - 运行时会话必须先 dispose 再删库行:`disposeSession` 会把在途轨迹**排干落库**,
         * 反过来做的话那次 flush 撞上已被级联删掉的 `sessions` 行,外键失败刷一屏错误日志。
         * - 正在回复中一律拒绝而不是硬删:那一轮的助手消息正等着写进这张表,
         * 删了只会让访客看到一句「本轮回复未能保存」。回 409,与 `/agent/ask` 的并发口径一致。
         * 
         * 【必须用 `claim()`,不能读一眼 `rec.busy` 就往下走】(codex 初审 P2)
         * `claim` 是**同步**的检查+置位,与 `/agent/ask` 用的是同一把闸:置位之后那个会话对
         * 逐出、空闲回收与并发 ask 都不可用。只读 `busy` 的话,另一个标签页的 ask 完全可以在
         * 「读到 false」与「dispose 完成」之间挤进来认领同一个会话,于是那一轮跑在一个正在被
         * 释放的 pi 会话上。认领失败 → 409,访客得到的是一句明确的「上一轮还在跑」。
         * 
         * 认领**不需要在成功路径上释放**:`disposeSession` 之后这条记录已经退出注册表,
         * `busy` 跟着它一起消失;只有「认领成功但后续步骤抛错」才需要还回去(见下面的 try/catch)。
         */
        public async deleteSession(id: string): Promise<DeleteSessionResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/agent/sessions/${encodeURIComponent(id)}`)

            //Populate the return object from the JSON body and received headers
            const rtn = await resp.json() as DeleteSessionResponse
            if (!BROWSER) {
                rtn.visitorCookie = mustBeSet("Header `set-cookie`", resp.headers.getSetCookie()[0])
            }
            return rtn
        }

        /**
         * 续接:单会话 + 历史消息回放。只能取到本访客自己的会话。
         */
        public async getSession(id: string): Promise<GetSessionResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/agent/sessions/${encodeURIComponent(id)}`)

            //Populate the return object from the JSON body and received headers
            const rtn = await resp.json() as GetSessionResponse
            if (!BROWSER) {
                rtn.visitorCookie = mustBeSet("Header `set-cookie`", resp.headers.getSetCookie()[0])
            }
            return rtn
        }

        public async image(method: "GET" | "HEAD", file: string, body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/agent/images/${encodeURIComponent(file)}`, body, options)
        }

        /**
         * 会话列表,按最近活跃倒序(工作台左栏)。**只有本访客的**。
         * 
         * 没有可认领的 cookie 时返回空列表而不是错误:一个没建过会话的访客看到的
         * 就该是「一个空站点」,而不是「你未登录」——站点没有登录这个概念。
         */
        public async listSessions(params: ListSessionsRequest): Promise<ListSessionsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit: params.limit === undefined ? undefined : String(params.limit),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/agent/sessions`, undefined, {query})

            //Populate the return object from the JSON body and received headers
            const rtn = await resp.json() as ListSessionsResponse
            if (!BROWSER) {
                rtn.visitorCookie = mustBeSet("Header `set-cookie`", resp.headers.getSetCookie()[0])
            }
            return rtn
        }

        /**
         * `GET /agent/tools` —— 工具目录。公开、无需鉴权,与其它访客端点同口径。
         * 不碰库,所以没有 `sensitive`(响应里本来就没有任何凭据或访客数据可脱敏)。
         */
        public async listTools(): Promise<ToolCatalogResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/agent/tools`)
            return await resp.json() as ToolCatalogResponse
        }
    }
}

export namespace metrics {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.track = this.track.bind(this)
        }

        public async track(method: "POST", body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/t`, body, options)
        }
    }
}

export namespace notes {
    export interface CategoryGroup {
        slug: string
        name: string
        /**
         * 分类圆点色,与 design token 一致
         */
        dot: string

        series: SeriesCard[]
    }

    export interface ChapterLink {
        slug: string
        label: string
        title: string
    }

    export interface ChapterSummary {
        slug: string
        label: string
        title: string
        /**
         * 置顶行(README)
         */
        pinned: boolean

        wordCount: number
        updatedAt: string
    }

    export interface GetChapterResponse {
        seriesSlug: string
        seriesName: string
        categorySlug: string
        categoryName: string
        slug: string
        label: string
        title: string
        /**
         * 标准 markdown(GFM);渲染在前端
         */
        contentMd: string

        wordCount: number
        /**
         * 第三方文章原链;自有内容为 null
         */
        sourceUrl: string | null

        publishedAt: string | null
        updatedAt: string
        prev: ChapterLink | null
        next: ChapterLink | null
    }

    export interface GetSeriesResponse {
        slug: string
        name: string
        description: string
        categorySlug: string
        categoryName: string
        chapterCount: number
        wordCount: number
        updatedAt: string | null
        chapters: ChapterSummary[]
    }

    export interface LatestItem {
        title: string
        seriesSlug: string
        chapterSlug: string
        updatedAt: string
    }

    export interface ListSeriesResponse {
        categories: CategoryGroup[]
        /**
         * 首页底部「最新 · …」行
         */
        latest: LatestItem[]
    }

    export interface SeriesCard {
        slug: string
        name: string
        description: string
        chapterCount: number
        /**
         * ISO 8601;空系列为 null(前端显示"整理中")
         */
        updatedAt: string | null
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.asset = this.asset.bind(this)
            this.categoryFeed = this.categoryFeed.bind(this)
            this.getChapter = this.getChapter.bind(this)
            this.getSeries = this.getSeries.bind(this)
            this.listSeries = this.listSeries.bind(this)
            this.siteFeed = this.siteFeed.bind(this)
        }

        public async asset(method: "GET" | "HEAD", series: string, file: string, body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/assets/notes/${encodeURIComponent(series)}/${encodeURIComponent(file)}`, body, options)
        }

        public async categoryFeed(method: "GET", file: string, body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/rss/${encodeURIComponent(file)}`, body, options)
        }

        public async getChapter(series: string, chapter: string): Promise<GetChapterResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/notes/series/${encodeURIComponent(series)}/chapters/${encodeURIComponent(chapter)}`)
            return await resp.json() as GetChapterResponse
        }

        public async getSeries(slug: string): Promise<GetSeriesResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/notes/series/${encodeURIComponent(slug)}`)
            return await resp.json() as GetSeriesResponse
        }

        public async listSeries(): Promise<ListSeriesResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/notes/series`)
            return await resp.json() as ListSeriesResponse
        }

        public async siteFeed(method: "GET", body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/rss.xml`, body, options)
        }
    }
}

export namespace system {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.health = this.health.bind(this)
        }

        /**
         * 健康检查 — 框架期唯一的实端点;其余服务(agent/trace/notes/admin/metrics)
         * 的接口形状在设计终稿确认后实现,职责与安全约束见各目录 README 与 docs/。
         */
        public async health(): Promise<{
    status: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/health`)
            return await resp.json() as {
    status: string
}
        }
    }
}

export namespace trace {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.stream = this.stream.bind(this)
        }

        public async stream(method: "GET", body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/trace/stream`, body, options)
        }
    }
}



function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}


// mustBeSet will throw an APIError with the Data Loss code if value is null or undefined
function mustBeSet<A>(field: string, value: A | null | undefined): A {
    if (value === null || value === undefined) {
        throw new APIError(
            500,
            {
                code: ErrCode.DataLoss,
                message: `${field} was unexpectedly ${value}`, // ${value} will create the string "null" or "undefined"
            },
        )
    }
    return value
}

function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "936eu-Generated-TS-Client (Encore/v1.57.13)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        return this.callAPI(method, path, body, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
            method,
            body: body ?? null,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}
